apiVersion: v1
kind: Service
metadata:
  name: screencast-recorder
  namespace: statex-apps
  labels:
    app: screencast-recorder
    managed-by: k8s-migration
spec:
  type: ClusterIP
  selector:
    app: screencast-recorder
  ports:
    - protocol: TCP
      port: 3391
      targetPort: 3391
      name: http
